### ISSUE TITLE
IP access list

### ISSUE THREAD

**Issue by stuart23** [astronomer/terraform-provider-astro#131] opened 2024-08-16 17:06 UTC
Can we expose the IP access list in the tf provider?

https://github.com/astronomer/terraform-provider-astro/blob/556d27e064bb5bf08b1524f0fcfa1d1092d37b67/internal/provider/models/organization.go#L13-L25

**Comment by chobberoni** [comment] 2024-08-19 15:52
duplicate of this https://github.com/orgs/astronomer/projects/113/views/7?sliceBy%5Bvalue%5D=IP+Access+List&pane=issue&itemId=73068646

**Comment by aliotta** [comment] 2024-08-19 15:53
Duplicate of another ticket we will get this done this quarter.

**Closed** 2024-08-19 15:52 UTC

**Comment by stuart23** [comment] 2024-08-19 16:30
Cheers!
